### ISSUE TITLE
Unsure if it's actually possible to message people on git.

### ISSUE THREAD

**Issue by MxOrbulent** [LoganDark/LoganDark#1]
So I'm just going to ask here in a issue:
Why are you insisting on using GNU GPL for all of your Fabric releases?
Fabric uses Apache License 2.0 for pretty much everything and for yarn they even went the extra mile and released as cc0. Spongepowered Mixins is under MIT... Why choose to lock it down?

I have yet to encounter a fabric repo of yours that uses GNU GPL code, so it's not the "I have to aspect" that one would encounter if they used GNU GPL code in their own code etc (which is why I never release anything under GNU GPL, not even LGPL).

**Comment by LoganDark** [comment]
I release my mods as GPL mainly so that any forks or other mods using my code stay free and open source. Is there an issue with GPL that I don't know about? Keep in mind that this is a significant step up from ARR.

**Comment by MxOrbulent** [comment]
Apache 2.0, CC0 and MIT accomplish the same goal of sharing code with the public (with MIT being bad in another way since it opens up for patent trolling and is to vague) without holding a gun to other developers heads and robbing them of their code.
GPL basically coerces people into releasing code the original author or authors had no part in making. How this is sane makes absolutely no sense. Imagine if someone gave you the keys to a car for free, but then come later and demand you pay him because you used the car to make uber deliveries. 
GPL's form of payment in this case is code.

When you release code into the public with some form of "for the public" sentiment, it leaves a poor taste in the mouth whereas you attach a condition that steals away other developers choices on what to do with their own code (that you did not make).
If I write 95% of the source code of a software, and then use GPL code for the remaining 5%, my project is now suddenly forced to also be GPL. 
If I don't, I violate the GPL license which woudl lead to legal action.

Somehow, those 5% suddenly think they are entitled to 95% of the work I made... Or thinking they are entitled to anything at all when they made the decision to release code. 
I donated a dollar to charity, now I'm entitled to be praised and get hugs...

People also seem to think that companies can suddenly lock away the original code you made avaible, but that's fear mongering from the FSF. At best it had some relevancy 30 years ago when digital computing was still fairly new and copyright laws thus were quite wonky.
You are still the original copyright holder of the code. At best they can only make a fork and relicense that, but they will never be able to take your original code and claim it as their own in some attempt to remove your copyright. On the flip side, whatever changes the company would have made to their fork is their own work. They can choose to release this back as a pull request. Or they don't. That's freedom.

It's also a difference of ideology in regards to "software". If I am going to release something for public use I'd much rather it being as free from constraints as is possible. GPL actually adds restrictions + it can only be used by people who actually like GPL.
I also find it highly ironic that GPL has no issues with taking code from Apache 2.0, MIT and so on, but won't extend the same kind of freedoms themselves. While the licenses allow this and are the entire point of having those licenses is freedom. It's still extremly ironic for a Foundation calling themselves "Freedom Software Foundation"...

Note, I would have had no issues with a LGPL ish solution where the mod code itself and any changes made to it also has to be released, or if you directly copy code from it (still inferior to apache 2.0 for example, but a improvement for sure), my problem is with that the GPL folks think they are entitled to my entire codebase or force licensing it as GPL, when such a user themself made a concious decision to release the code to the public. Me using code you release publically are not entitlement in turn, you yourself choose to release it. I never asked you to release it publically. Entitlement from my end would be me demanding you relicense it. Here I am asking you and giving a reason as to why GPL is not good.

But with GPL, it becomes a "I'm gonna hold a gun to your head and everyone is entitled to your entire project if you dare use anything from my gpl licensed code".
This is why I left spigot in the first place, the GPL license is not compatible with what I think freedom should be like (not to mention that the gpl license is heavily abused over there, further eroding it's legitimacy, the premium plugin section is a goldmine for any lawyer that would bother with it, it's forbidden to encrypt and deny others access to GPL licensed code, something they do over there all the time, crazy).

Fabric is genuinly a breath of fresh air in terms of it's licensing. Yarn especially is the most impressive where they straight up went public domain. Now everyone no matter who they are or what they think has access to mappings. That's great. 
If it had been released under GPL, you need to force yourself to use GPL too.

I don't have to worry a single bit. Since it also makes use of a similar thing to GPL (the more contributors, the harder it is to relicense the entire thing) but because it is under a more permissive license, I actually have legal options to earn money on my own work. FSF's "hurr durr u can sell" argument for GPL is based on when internet access was scarce, uber slow and mostly unavaible, and people were forced to buy CD's to get at your code. Things do not work like that today. I could sell the first "CD" and then I won't see a single penny in income ever again. I could offer support, but as a lone single person, this is not a feasible way to put bread at the table.

I hoped most devs would jump along with using similar licenses. Some did, and some stick to the same old "because it's default" thinking or don't actually think trough the consequences of using GPL just because they feel they should have some sort of license (which I attribute to a nice propaganda work by the FSF, Microsoft would be proud). While you have atleast thinked it trough, many people don't consider what they are doing with licenses at all when making software. 
This is why the bukkit implosion happened (it happened for the right reasons, but it caused a massive clusterfuck for multiplayer in minecraft all over the world for a good while) and also a example of why copyright is so strong.

Only something like CC0 or a strongly worded legal document where you make it absolutely clear that you waive the work to public domain could end this copyright you have. However it must be very intentional and clear. Besides a "copyright assignment", loosing your copyright is very very very hard. It's also why GPL and most other licenses actually can work, they build ontop of copyright, and because the copyright is so strong, they in turn get strong too. This is why GPL does not include any public domain waiver, because they want your code in their ecosystem. And thus you remain a copyright owner. If it included a public domain clause such as cc0 does, GPL would not work.

You are free of course to continue using GPL (People are under some magic spell whereas they think FSF holds copyright over your code, it is not so). 
But consider it. If you don't like it, you can switch back easily to GPL. Any current and older versions would be under GPL (and that code would remain under GPL terms), your new version would be under whatever license you choose, and if you switch back to GPL, future versions would be GPL again. You could even dual license the code if you wished to do so. You could technically even dual license the code right now. Keep one edition as GPL, the other as Apache 2.0 or something similar that is more permissive. Aslong as the dev then obtains a copy of the code under the Apache 2.0 or something similar, then everything is fine and dandy. And you can still have the other under GPL. However after that point, anything made for the GPL side would not be useable by those who obtained a copy with apache 2.0, if one intended to upkeep both versions, it would be additional work, that is true.

(Note that this entire thing becomes a entirely different cake the moment you have even a single contributor, in order to regain full control. You'd need to remove any code made by that contributor. In special regards to Linux, this is one of the few times GPL is good for a project and something I approve of. Because it is now effectively impossible for anyone, even Linus Torvald to have full control over the code, atleast until the contributed code is 70 years old, then you will see a clusterfuck of epic proportions).

This is how most business does it today because GPL on it's own is way way to restrictive, but nothing says someone releasing a fabric mod cannot use the same principles of dual licensing to accomplish a similar goal.

This got kind of long, apologies.

**Comment by LoganDark** [comment]
Do you think someone's going to take one of my mods and write so much extra that my code is going to be 5% of their project? Genuinely curious. Using GPL for small libraries isn't the same as using it for a Fabric mod, which is standalone.

I license my mods under GPL so that derivative works stay open-source - not to hold a gun to anyone's head if they decide to include my mod in their huge 5-million-line proprietary project (which is never, ever going to happen).

One thing I have spotted thanks to your issue is https://github.com/LoganDark/fabric-camera-shake, which is a library that is under GPL rather than LGPL or otherwise. If you like, I can change that since I'm the only one who has written code for that library.

**Comment by MxOrbulent** [comment]
Even if it was the reverse, that your fabric mod consisted of 95% of the project, it would still make no sense to demand that the other dev give up their own code that is not part of your fabric mod. That's the very definition of having a gun held to your head. "Do this or else!!!". The only out is to simply not use the GPL code at all. 

The code you wrote (and any changes that might be made to it by someone else) I have absolutely no issues with. If the dev author changes stuff or adds code to the GPL work, I have no issues with them being bound to release these changes under GPL.

However, if I were to say use one of your classes as a utility class, I am now bound to release the entirety of my project under GPL too. LGPL in this case is atleast a improvement.

**Comment by LoganDark** [comment]
> it would still make no sense to demand that the other dev give up their own code that is not part of your fabric mod

_If_ they're distributing a modified version of my mod, it makes perfect sense to me. I don't think the GPL demands you even host your code on GitHub or provide any code to people who don't own the binary. It's just that I want any modified copies of my mods in circulation to have accompanying code, that's all.

I'm pretty hands-off about my licensing. I just chose GPL because it keeps everything open source. I think most of my other things are MIT. Some of them might be accidentally ARR but I'd add a license if anyone asked.

> However, if I were to say use one of your classes as a utility class, I am now bound to release the entirety of my project under GPL too. LGPL in this case is atleast a improvement.

Yes, LGPL would allow you to depend on my mod and use the utility class without having to release your own source code. If there are any utility classes you have your eye on, I could consider releasing them under a separate license. But for now, GPL seems like the best choice for me.

If your essay is any indication, it's not necessarily the best choice for you, or the open source community, but that's subjective. The only part that really concerns me is what happens to my code out in the open. That's probably selfish, but I think that's okay.

I (probably) won't be relicensing my mods.

**Comment by MxOrbulent** [comment]
That's fine. Thanks for the discussion.

**Comment by LoganDark** [comment]
If you want to use something from one of my mods and find the license to be an issue, I'd be glad to help. But as for the public source that everyone sees, that will stay GPL
